version: '2.1'

services:
  geoguess:
    build: .
    # image:
    environment:
#      - VUE_APP_PUBLIC_PATH=/
#      - VUE_APP_FIREBASE_MEASUREMENT_ID=measurment
#     Read variables from .env
      - VUE_APP_LIST_MAPS_JSON_URL=${VUE_APP_LIST_MAPS_JSON_URL}
      - VUE_APP_API_KEY=${VUE_APP_API_KEY}
      - VUE_APP_FIREBASE_API_KEY=${VUE_APP_FIREBASE_API_KEY}
      - VUE_APP_FIREBASE_PROJECT_ID=${VUE_APP_FIREBASE_PROJECT_ID}
      - VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${VUE_APP_FIREBASE_MESSAGING_SENDER_ID}
      - VUE_APP_FIREBASE_APP_ID=${VUE_APP_FIREBASE_APP_ID}
      - VUE_APP_FIREBASE_AUTH_DOMAIN=${VUE_APP_FIREBASE_AUTH_DOMAIN}
      - VUE_APP_FIREBASE_DATABASE_URL=${VUE_APP_FIREBASE_DATABASE_URL}
      - VUE_APP_STORAGE_BUCKET=${VUE_APP_STORAGE_BUCKET}
    ports:
      - 3000:80
  proxy:
    image: beevelop/nginx-basic-auth
    links:
      - "geoguess:web"
    ports:
      - 9000:80
    environment:
      - HTPASSWD=gabri:$$apr1$$9oq1w35f$$MXPEe9MYq8W42ZTRXKsLK1
